### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by salaheddinegit** [AnchorFreePartner/hydrasdk-demo-ios#12]
Failed to connect to Hydra. Error was: Error Domain=com.anchorfree.hydra.manager Code=4 "failed_to_connect" UserInfo={NSLocalizedDescription=failed_to_connect}

**Comment by Vladbruno** [comment]
Hi. Did u fix this problem? I have the same one...

**Comment by ammar97s** [comment]
@salaheddinegit @Vladbruno fixed it? I also have the same issue.
