### ISSUE TITLE
Undefined symbols for architecture arm 64

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-ios#17]
Hello, 
After update xcode to 12.0.1 and try to add firebase to pod this issue happened with me when building.
Please help me to fix this issue
![527F999B-0649-4843-A03B-B425D83165B5](https://user-images.githubusercontent.com/33099498/95012895-9a368200-063c-11eb-8bda-242ae67847cf.jpeg)

**Comment by TheSooth** [comment]
Hello,
you need to link libresolv to your network extension target.

**Comment by mwaked** [comment]
@TheSooth Thanks for your response, 
Can you please help me how to link it to my network extension target, I searched but found nothing, i use xcode 12.0.1
