### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by mwaked** [AnchorFreePartner/hydrasdk-demo-ios#18]
Hello,
I logged in successfully and get all servers but when i try to connect this error shown to me, Please help me to fix this issue.
Thanks.

```
   private func startVPN() {
               self.hydraClient.start(location: country) { (e, _) in
                   if let ex = e {
                       print("Restart VPN error: \(ex)")
                   } else {
                       print("Restart VPN success, country: \(self.country?.code ?? "unknown")")
                   }
                   self.countryConnectedTo = self.country
                  
                // update ui 
               }
           }
           
           private func stopVPN(completion: ((Error?) ->())? = nil) {
               hydraClient.stop { (e) in
                   if let ex = e {
                       print("Stop VPN error: \(ex)")
                   } else {
                       print("Stop VPN success")
                   }
                   completion?(e)
               }
           }
```

<img width="668" alt="Screen Shot 2020-10-22 at 3 21 45 PM" src="https://user-images.githubusercontent.com/33099498/96877744-53d58580-147a-11eb-82d4-34e78bba6eb2.png">

**Error Log:**
2020-10-22 15:15:44.794964+0200 RocketVPN[22060:5706587] [] nehelper sent invalid result code [1] for Wi-Fi information request
2020-10-22 15:15:44.797807+0200 RocketVPN[22060:5706587] [] nehelper sent invalid result code [1] for Wi-Fi information request
2020-10-22 15:15:44.800245+0200 RocketVPN[22060:5706618] []  Failed to load configurations: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
Restart VPN error: Error Domain=NEVPNErrorDomain Code=5 "permission denied" UserInfo={NSLocalizedDescription=permission denied}

**Comment by TheSooth** [comment]
Hey, try to install the VPN profile before starting the connection
