### ISSUE TITLE
TRAFFIC_EXCEED

### ISSUE THREAD

**Issue by ponomarew** [AnchorFreePartner/hydrasdk-demo-ios#21]
I have a premium plan, configured payment method for apple. Then I buy a subscription via in-app purchase but traffic still limited. In the purchases tab, it says that "User has no purchases". Any advice?

**Comment by DeeptiChawla35** [comment]
I have a premium plan, configured payment method for apple. Then I buy a subscription via in-app purchase but traffic still limited....after purchasing the Subscription then receipt is not verified on hydra SDK everytime got invalid purchase.Please let me know any solution?
