### ISSUE TITLE
TRAFFIC_LIMIT

### ISSUE THREAD

**Issue by DeeptiChawla35** [AnchorFreePartner/hydrasdk-demo-ios#22]
I have a premium plan, configured payment method for apple. Then I buy a subscription via in-app purchase but traffic still limited....after purchasing the Subscription then receipt is not verified on hydra SDK everytime got invalid purchase.Please let me know any solution?

**Comment by TheSooth** [comment]
Hello!

Could you please provide your carrierID, I would check purchases on our side.

**Comment by DeeptiChawla35** [comment]
Hi,
Please find the carrier id : qua_fastvpn

**Comment by TheSooth** [comment]
Please, try to call `purchase` method with your purchase token

**Comment by DeeptiChawla35** [comment]
> Please, try to call `purchase` method with your purchase token

I already used this method but didn't got any success always getting the response "invalid purchase".

**Comment by DeeptiChawla35** [comment]
I have purchased it from Sandbox account for Apple.Let me know if I can purchase from the Sandbox for testing Purpose.

**Comment by TheSooth** [comment]
how are you sending the receipt? try to encode receiptData into base64 encoded string.

**Comment by DeeptiChawla35** [comment]
I have tried in JSON format.

**Comment by TheSooth** [comment]
try to encode receiptData into base64 string and then use it as token value in `purchase` call :)

**Comment by DeeptiChawla35** [comment]
thankyou so much.. issue is resolved now its working fine.

**Comment by DeeptiChawla35** [comment]
Hi,
Please suggest me, if my subscription is expired then how to remove the traffic unlimited on particular user.
