### ISSUE TITLE
SUBSCRIPTION_EXPIRED_REMOVE_TRAFFIC_LIMIT

### ISSUE THREAD

**Issue by DeeptiChawla35** [AnchorFreePartner/hydrasdk-demo-ios#23]
Hi,
Please suggest me, if my subscription is expired through Apple then how to remove the traffic unlimited on particular user.

**Comment by TheSooth** [comment]
hey, it should be updated automatically.

**Comment by DeeptiChawla35** [comment]
ok I have purchased through Sandbox for weekly it is valid for only 3 minutes, but after 3 minutes got the traffic is "UNLIMITED" so please let me know when will get the traffic is limited.

**Comment by TheSooth** [comment]
subscriptions are updated once in a day as i remember.

**Comment by DeeptiChawla35** [comment]
Hi,
As per documentation, "delete" purchase function is given but in a SDK I am not finding the "delete purchase" function so can you please help me how to find this function in SDK.

**Comment by TheSooth** [comment]
hey,
where did you found that? we don't have this function.
