### ISSUE TITLE
 Found an unexpected Mach-O header code: 0x72613c21

### ISSUE THREAD

**Issue by ammar97s** [AnchorFreePartner/hydrasdk-demo-ios#28]
ValidateEmbeddedBinary /Users/syedshayanjamal/Library/Developer/Xcode/DerivedData/HydraSDKDemo-bwjloldeuvpmttbjqolvnxbfrxbt/Build/Products/Debug-iphoneos/HydraSDKDemo.app/PlugIns/neprovider.appex (in target 'HydraSDKDemo' from project 'HydraSDKDemo')
    cd /Users/syedshayanjamal/Desktop/Development/ODL/practice/new\ vpn/hydrasdk-demo-ios-master
    /Applications/Xcode.app/Contents/Developer/usr/bin/embeddedBinaryValidationUtility /Users/syedshayanjamal/Library/Developer/Xcode/DerivedData/HydraSDKDemo-bwjloldeuvpmttbjqolvnxbfrxbt/Build/Products/Debug-iphoneos/HydraSDKDemo.app/PlugIns/neprovider.appex -signing-cert 56972FD7EED56A44390D199F149955F3D3E4B72A -info-plist-path /Users/syedshayanjamal/Library/Developer/Xcode/DerivedData/HydraSDKDemo-bwjloldeuvpmttbjqolvnxbfrxbt/Build/Products/Debug-iphoneos/HydraSDKDemo.app/Info.plist

**Comment by nikviradiya26** [comment]
Hello @ammar97s, were you able to go through this?

**Comment by ammar97s** [comment]
Hello @nikviradiya26, were you able to resolve it? I am still not able to resolve this issue

**Comment by TheSooth** [comment]
@ammar97s which carrierID are you using?

**Comment by ammar97s** [comment]
I created my own project on portal. Using it's carrier id

**Comment by ammar97s** [comment]
@TheSooth

**Comment by TheSooth** [comment]
Please, contact the support with your carrierID

**Comment by ammar97s** [comment]
It's not carrier id issue. I have tried another premium carrier id with unlimited traffic. But the issue is there

**Comment by TheSooth** [comment]
If you need a fix, you should contact support with your carrierID and also please, mention carrier with unlimited traffic.

**Comment by ammar97s** [comment]
Support url ?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by TheSooth** [comment]
You could find in on portal where you have created you're carrierID
