### ISSUE TITLE
Network extension entitlement for free Apple dev account?

### ISSUE THREAD

**Issue by ink-splatters** [AnchorFreePartner/hydrasdk-demo-ios#29]
Hello,

thanks a lot for the demo.

Is there any theoretical chance to enable "network extension" entitlement for free dev account, without jailbreak?

(I assume not using 0-day(s) available up to iOS 15.0.1 which probably could ease it?)

Kind regards,
is

**Comment by TheSooth** [comment]
Hello, no, it isn’t possible
